### PR TITLE
Add structure for new EoS

### PR DESCRIPTION
**Pull request by gassmoeller**
This adds a template for a new EoS that is read in from a file (like the ones in pull request #9). I did not test the implementation because I was not sure which file from #9 to use, but the structure should work. @mnakajima7 could you take a look? I left some todos for you (like which particles will get this new EoS), and I am sure there are bugs inside, but if you get stuck using this let me know.

In its current state the PR does not compile, we first need a data file, before this can be cleaned up and merged.

### CODE REVIEW

**Comment by mikinakajima** [comment]
Hi Rene, thank you so much for your help! But I did get stuck.. I thought the last line in EoS.h should be 
"static const EoS::ANEOS <<PS::F64>> ANEOS_Granite     ("../eos/granite_rho_u.txt");" or some sort. The ../eos/granite_rho_u.txt file looks like:
   1 Density (kg/m3) Temperature (K) Energy (J/kg) Pressure (Pa) Sound speed (m/s) Entropy (J/kg/K)
   2   0.100000000000E-05  0.100000000000E+01  0.117199485934E+04  0.197173850220-101  0.100000000000E-11 -0.522510115956E+04
   3   0.100000000000E-05  0.100000000000E+02  0.115860413333E+05  0.197173850220E-99  0.100000000000E-11 -0.255328149052E+04
....
Then I encountered the following compiling error;

In file included from main.cpp:12:
EoS.h: In instantiation of 'EoS::ANEOS<type>::ANEOS(const string&) [with type = double; std::__cxx11::string = std::__cxx11::basic_string<char>]':
EoS.h:197:79:   required from here
EoS.h:146:6: error: passing 'const std::vector<std::vector<std::array<double, 6>, std::allocator<std::array<double, 6> > >, std::allocator<std::vector<std::array<double, 6>, std::allocator<std::array<double, 6> > > > >' as 'this' argument discards qualifiers [-fpermissive]
      eos_data.push_back(std::vector<std::array<type,6> >());
      ^~~~~~~~
In file included from /usr/local/Cellar/gcc/8.2.0/include/c++/8.2.0/vector:64,
                 from ../FDPS/src/ps_defs.hpp:4,
                 from ../FDPS/src/particle_simulator.hpp:3,
                 from main.cpp:1:
/usr/local/Cellar/gcc/8.2.0/include/c++/8.2.0/bits/stl_vector.h:1090:7: note:   in call to 'void std::vector<_Tp, _Alloc>::push_back(std::vector<_Tp, _Alloc>::value_type&&) [with _Tp = std::vector<std::array<double, 6>, std::allocator<std::array<double, 6> > >; _Alloc = std::allocator<std::vector<std::array<double, 6>, std::allocator<std::array<double, 6> > > >; std::vector<_Tp, _Alloc>::value_type = std::vector<std::array<double, 6>, std::allocator<std::array<double, 6> > >]'
       push_back(value_type&& __x)
....

I bet this is a very basic question, but my shallow understanding of C++ makes it a bit difficult to solve this compiling error. Would you mind giving advice on this? Sorry!

**Comment by gassmoeller** [comment]
Hi Miki,
sorry it took so long, it was really just a small error on my side. The member variables `eos_data`, `densities`, and `energies` can not be `const` as in my earlier version, because we do not know them during initialization (we only know them once we read the data file). I corrected that in my new commit. You can either pull the new version of this PR, or make the small changes yourself. Let me know if you find more problems.

**Comment by mikinakajimav2** [comment]
g++ (MacPorts gcc45 4.5.4_12) 4.5.4
I think I am still having this compiling error message:
Building main.cpp ...
In file included from main.cpp:12:0:
EoS.h:93:27: error: 'array' is not a member of 'std'
EoS.h:93:27: error: 'array' is not a member of 'std'
EoS.h:93:45: error: template argument 1 is invalid
EoS.h:93:45: error: type/value mismatch at argument 2 in template parameter list for 'template<class _Tp, class _Alloc> class std::vector'
EoS.h:93:45: error:   expected a type, got '6'
EoS.h:93:47: error: template argument 1 is invalid
EoS.h:93:47: error: template argument 2 is invalid
EoS.h:93:49: error: expected unqualified-id before '>' token
EoS.h: In member function 'std::pair<unsigned int, unsigned int> EoS::ANEOS<type>::get_table_index(type, type) const':
EoS.h:111:9: error: 'line' does not name a type
EoS.h:112:68: error: 'line' was not declared in this scope
EoS.h:113:9: error: 'column' does not name a type
EoS.h:114:69: error: 'column' was not declared in this scope
EoS.h: In constructor 'EoS::ANEOS<type>::ANEOS(const std::string&)':
EoS.h:127:37: error: no matching function for call to 'std::basic_ifstream<char>::open(const std::string&, const std::ios_base::openmode&)'
/opt/local/include/gcc45/c++/fstream:526:7: note: candidate is: void std::basic_ifstream<_CharT, _Traits>::open(const char*, std::ios_base::openmode) [with _CharT = char, _Traits = std::char_traits<char>, std::ios_base::openmode = std::_Ios_Openmode]
EoS.h:144:6: error: 'eos_data' was not declared in this scope
EoS.h:144:37: error: 'array' is not a member of 'std'
EoS.h:144:37: error: 'array' is not a member of 'std'
EoS.h:144:54: error: template argument 1 is invalid
EoS.h:144:54: error: type/value mismatch at argument 2 in template parameter list for 'template<class _Tp, class _Alloc> class std::vector'
EoS.h:144:54: error:   expected a type, got '6'
EoS.h:144:58: error: expected primary-expression before ')' token
EoS.h:149:5: error: 'eos_data' was not declared in this scope
EoS.h:149:36: error: 'array' is not a member of 'std'
EoS.h:149:51: error: expected primary-expression before ',' token
EoS.h:149:55: error: expected primary-expression before ')' token
EoS.h: In member function 'type EoS::ANEOS<type>::Pressure(type, type) const':
EoS.h:175:11: error: 'eos_data' was not declared in this scope
EoS.h: In member function 'type EoS::ANEOS<type>::SoundSpeed(type, type) const':
EoS.h:181:11: error: 'eos_data' was not declared in this scope
EoS.h: In constructor 'EoS::ANEOS<type>::ANEOS(const std::string&) [with type = double, std::string = std::basic_string<char>]':
EoS.h:190:86:   instantiated from here
EoS.h:152:35: error: 'stream' has incomplete type
make: *** [main.o] Error 1

**Comment by mikinakajimav2** [comment]
I am trying with g++ (MacPorts gcc49 4.9.3_0) 4.9.3
Building main.cpp ...
In file included from /opt/local/include/gcc49/c++/cmath:44:0,
                 from ../FDPS/src/ps_defs.hpp:3,
                 from ../FDPS/src/particle_simulator.hpp:3,
                 from main.cpp:1:
/opt/local/lib/gcc49/gcc/x86_64-apple-darwin14/4.9.3/include-fixed/math.h:45:23: fatal error: sys/cdefs.h: No such file or directory
 #include <sys/cdefs.h>
                       ^
compilation terminated.
make: *** [main.o] Error 1

**Comment by mikinakajima** [comment]
Hi Rene,

I noticed that the current version experiences an immediate segmentation fault in Line 149 (EoS.h):
149                                 eos_data[line_index].push_back(std::array<type,6>());

I added 
   eos_data.push_back(std::vector<std::array<type,6> >());

before Line 149 and it seems to work for a bit. Then I can see another segmentation fault occurs during the setup. I will look into it tomorrow before the meeting.

Thank you so much :) !!

**Comment by mikinakajima** [comment]
I think the segmentation fault is happening in Line 178 (EoS.h)

175                 inline type Pressure(const type dens, const type eng) const{
176                         const std::pair<unsigned int, unsigned int> data_index = get_table_index(dens, eng);
177 
178                         return eos_data[data_index.first][data_index.second][3];
179                 }

I think getting the indexes part is not working, but I am not sure how to fix it yet ..
 get_table_index(const type density, const type energy) 

By the way I have a stupid question -- I originally thought eos_data would be 2D, but this seems 3D? Am I understanding this correctly?

eos_data[data_index.first][data_index.second][3]

I will learn C++ in the meantime :D

**Comment by gassmoeller** [comment]
Hi Miki, yes sorry in my implementatio were two index bugs. Your fix avoided one of the issues but introduced an empty vector entry, and maybe that was causing the other error. Could you try again with my newly updated version?

**Comment by mikinakajima** [comment]
Thank you Rene! I tried, but I still have a segmentation fault at
                               eos_data[current_line_index].push_back(std::array<type,6>());
I wonder if I am doing something wrong

**Comment by gassmoeller** [comment]
Ah, found it. No you are doing everything right, the code is wrong. Let me think about a good solution, but for now it should be enough to put an empty line at the beginning of the data file (between the comment header and the first actual data line). Let me know how that goes.

**Comment by mikinakajima** [comment]
These are the additional changed I made in the code:
In EoS.h

static const EoS::ANEOS<PS::F64> AGranite     ("granite.rho_u.txt");

In init/GI.h

Lines
139                                         ith.setPressure(&AGranite);
180                                         ith.setPressure(&AGranite);
237                                 sph_system[i].setPressure(&AGranite);

(sorry this comment looks ugly but I didn't want to "commit" my code)

**Comment by gassmoeller** [comment]
Oh, and could you let me know which modifications you made to actually test the reader? I.e. how do you run the model and with what aneos file. I have a `quarzite.table.txt` that you send me a while back, can I use that for testing? Do I need to change anything else?

**Comment by gassmoeller** [comment]
Looks like you read my mind :smile:. But I do not have the granite table, could you send that to me, or can I also use the quarzite table I already have?

**Comment by mikinakajima** [comment]
[granite.rho_u.txt](https://github.com/NatsukiHosono/FDPS_SPH/files/2891889/granite.rho_u.txt)

Yes!

**Comment by mikinakajima** [comment]
I completely forgot about the quarzite.table.txt :D Would you mind sending it to me??

**Comment by gassmoeller** [comment]
See below. I also found the problem. The granite and quarzite table are differently formatted and I wrote the algorithm to read the quarzite table. Specifically I rely on an empty line to signal the next 'row' of the table. We should settle on a file format. Is it more convenient for you to have empty rows whenever you jump to the next higher density, or do you prefer to spell out the number of rows and columns in the header as you do in the granite table? Both would work, but the code would need to look different.

[quarzit.table.txt](https://github.com/NatsukiHosono/FDPS_SPH/files/2891927/quarzit.table.txt)

**Comment by mikinakajima** [comment]
I see. I wrote a python script that converts quarzit.table.txt  to the format I was using. The reason is that this  quarzit.table.txt  format is only using rho and T to search internal energy etc, but it is more straightfoward for SPH to use rho and U as an input. A while ago I wrote a python script to make this conversion, but I don't think it made it to the master version. 

The python code is here (in the eos branch)
https://github.com/NatsukiHosono/FDPS_SPH/blob/eos/eos/ANEOS_conversion.py

**Comment by mikinakajima** [comment]
And I would be happy to change the python code to have a blank between different rho values. Anyways I will see you guys in ... 3 mins :)

**Comment by gassmoeller** [comment]
I changed the ANEOS EoS to read the new format (the one from the granite table you linked above Miki). It seems to work for me (no crashes, and the data that is read in and assigned to the particles looks ok to). However, when I visualize the results I only see one planet. Is that my setup or did something go wrong? Miki could you check if the current version gives you the results you expect?

**Comment by mikinakajima** [comment]
Hi Rene, thank you soooo much! Yes it did work. And I did see the same problem you have. I changed the code a bit and now it seems to be working; in GI.h, I commented out the if statement. By the default setting, the impactor particle seems not to be taken into account.

214                 //if(createTarget == true){
215                         for(PS::U32 i = 0 ; i < tar.size() ; ++ i){
216                                 ptcl.push_back(tar[i]);
217                         }
218                 //}else{
219                         for(PS::U32 i = 0 ; i < imp.size() ; ++ i){
220                                 ptcl.push_back(imp[i]);
221                         }
222                 //}

**Comment by mikinakajima** [comment]
OK, now I realized that probably "createtarget" option is to make the initial condition of the target. Same for an imapctor. Nonetheless, I feel like we need to create another option when we want to perform an actual impact simulation. Natsuki, let me know if I am missing something here.. also, where can I modify the time interval to produce output files?

**Comment by mikinakajima** [comment]
Another thing I realized is that again the current FDPS version is not compatible with the code. I am not sure why this keeps happening :/ We may want to keep our own FDPS version??

**Comment by mnakajima7** [comment]
Alright, I am so sorry, I just realized that granite.rho_u.txt didn't have the pressure!! I added the pressure row.
[granite.rho_u.txt](https://github.com/NatsukiHosono/FDPS_SPH/files/2943524/granite.rho_u.txt)

**Comment by mikinakajima** [comment]
I realized that the original granite.rho_u.txt did not have the pressure... I am so sorry. I am putting one with Pressure here

[granite.rho_u.txt](https://github.com/NatsukiHosono/FDPS_SPH/files/2943533/granite.rho_u.txt)

**Comment by mikinakajima** [comment]
OK... now then the code experiences a segmentaiton fault with the new input file. I will look into it

**Comment by mikinakajima** [comment]
I solved it; please use this instead. I will stop mumble here :D 
[granite.rho_u.txt](https://github.com/NatsukiHosono/FDPS_SPH/files/2943678/granite.rho_u.txt)

**Comment by gassmoeller** [comment]
Hi all,
I checked the input routine and found another bug that shifted the data fields for higher densities. Miki could you give the new version another try?

I have added a routine that allows testing the input. It writes a new file 'test_output.txt' in the folder where you start the model. This file contains the content of the internal memory that was read from the aneos file (it is the result of the cycle 'read'->'parse'->'store'->'write') and it is identical to the input file, except the E is replaced by e, and there is another space at the end of each line.
Let me know if this version works.

**Comment by mikinakajima** [comment]
Hi Rene, 
Thank you for the edit and I am sorry it took forever to respond! It seems there is still a difference; the x-axis is the density and y-axis is the pressure. The blue is the SPH output and yellow is the ANEOS data. Please let me double check this output -- I will keep you posted.
Screen Shot 2019-04-02 at 6 16 37 PM

**Comment by gassmoeller** [comment]
Hmm that is unfortunate. Lets discuss how we can further test this this afternoon. Are we set for a zoom meeting later today?

**Comment by mikinakajima** [comment]
Yes! This may be just my problem and I am trying to solve it before the meeting. Thank you!

**Comment by mikinakajima** [comment]
Good news! My code was being stupid. Now they seem to agree, but somehow there is some offset. I will try to figure that part out before the meeting.
Screen Shot 2019-04-04 at 6 11 17 PM

**Comment by mikinakajima** [comment]
I plotted density vs. sound speed. There still seems to be some offset. I suspect there may be an offset in the temperature estimate. Would it be possible to produce an output with temperature?

Screen Shot 2019-04-04 at 7 45 30 PM

**Comment by gassmoeller** [comment]
Hmm, depends what you mean by output with temperature. By FDPS SPH? Whenever temperature is involved I am suspicious of Kelvin vs Centigrade conversions, any possibility that is happening somewhere?
I have opened a zoom meeting and send you the link, lets chat about it.

**Comment by mikinakajima** [comment]
[granite.rho_u.txt](https://github.com/NatsukiHosono/FDPS_SPH/files/3045890/granite.rho_u.txt)

**Comment by mikinakajima** [comment]
Sorry, quick question; does EoS.h assume 120 density mesh x 120 internal energy mesh? I ran with 120 density mesh x 240 internal energy mesh and it seems to be having some problem, but it may be an issue on my end. I just wanted to double check

**Comment by gassmoeller** [comment]
No there is no internal assumption about the mesh size. Did you change the header of the file where you specify the number of points in each direction?

**Comment by mikinakajima** [comment]
I did. Let me double check what I have done. Will get back to you

**Comment by gassmoeller** [comment]
I did add the linear interpolation we discussed yesterday. First tests look ok, but I do not have a good way to systematically test it. Maybe you could give it a try with your script and let me know if the result improves?

**Comment by mikinakajima** [comment]
Sorry - i should have gotten back to you sooner, but it does look great!

Screen Shot 2019-05-06 at 3 04 35 PM

**Comment by mikinakajima** [comment]
Somehow I cannot post a python script here, so I am converting it to a text file. This is the script I used to produce the figure above. sorry it's a bit messy now..


[ANEOS_calc_P.txt](https://github.com/NatsukiHosono/FDPS_SPH/files/3149546/ANEOS_calc_P.txt)
[granite.rho_u.txt](https://github.com/NatsukiHosono/FDPS_SPH/files/3149547/granite.rho_u.txt)
[granite.table.txt](https://github.com/NatsukiHosono/FDPS_SPH/files/3149548/granite.table.txt)

**Comment by mikinakajima** [comment]
Also, I wrote a higher res EoS table (120x240) (density grid 120, internal energy grid 240), but I don't think the SPH program is reading this correctly. For example, see result/00000_00001_00000.dat. On the line #3, Density, internal energy, pressure are;   2620.235882     6253125.012877  6216.548527. However, the pressure should be actually order of  ~2.5E10 (from the data table, density, internal energy, pressure are; 2.60625251E+03  6.27761248E+06  2.50594066E+10, line 15987, granite.rho_u.HR.txt). I haven't quite figured out why this is the case yet. The previous lower res table (120x120) is working fine.

[granite.rho_u.HR.txt](https://github.com/NatsukiHosono/FDPS_SPH/files/3149849/granite.rho_u.HR.txt)

**Comment by mikinakajima** [comment]
Lower resolution 

[granite.rho_u_120_60.txt](https://github.com/NatsukiHosono/FDPS_SPH/files/3150271/granite.rho_u_120_60.txt)

**Pull request merged**
